### ISSUE TITLE
Choosing the same picture after reset

### ISSUE THREAD

**Issue by AhmedEmadAhmedABD** [bupy7/js-cropbox#11]
I am facing strange behavior after reset :  
1- browse image and load it.
2- press reset.
3- try to choose the same image again 

you will find that image doesn't load until you choose another one.
is there any solution for this?

**Comment by bupy7** [comment]
@AhmedEmadAhmedABD I have not the same behavior. What your browser?

**Comment by AhmedEmadAhmedABD** [comment]
chrome . it happens will browsing but I am use start code in on change event to load image automatically with no need to press start.

**Comment by bupy7** [comment]
@AhmedEmadAhmedABD After load some image your file input caching. Therefore, you need reset cache of your file input manually before load new image.

**Comment by AhmedEmadAhmedABD** [comment]
Thanks a lot . form reset solved the problem. thanks for your rapid support.

**Comment by bupy7** [comment]
@AhmedEmadAhmedABD can reset only input file like:

```js
fileInput.files[0] = null;
```
I think that. But I didn't test it =)

https://developer.mozilla.org/en-US/docs/Web/API/FileList

**Comment by AhmedEmadAhmedABD** [comment]
I tried it but doesn't work .
calling the following after reset solved the issue : 
`this.form.reset();`

**Comment by bupy7** [comment]
@AhmedEmadAhmedABD hm... ok... what about

```js
fileInput.value = null;
```

?

**Comment by AhmedEmadAhmedABD** [comment]
Yes . this works perfectly . thanks a lot again.
